<?php
/**
 * @package     Arc
 * @subpackage  Core
 * @copyright   Copyright (C) 2005 Punnet. All rights reserved. See COPYRIGHT_ARC.txt
 * @license     http://www.gnu.org/licenses/gpl.html GNU/GPL. See LICENSE_ARC.txt
 * Arc is free software: you can redistribute it and/or modify
 * it under the terms of version 3 of the GNU General Public License
 * as published by the Free Software Foundation.
 * The disclaimer of warranty as stated in the GPL applies to this program
 */

defined( '_JEXEC' ) or die( 'Restricted access' );

/**
 * Repository of library function common to both the
 * admin and component sides of the Apotheosis core component
 *
 * @author     lightinthedark <code@lightinthedark.org.uk>
 * @package    Apotheosis
 * @subpackage Core
 * @since 0.1
 */
class ApotheosisData
{
	// #############  Data access functions for use with data_access files in various helpers  ############
	
	/**
	 * Calls the data_access function indicated by $ident.
	 * Passes any other params through to the receiving function.
	 * 
	 * @param string $ident  The component.function to call
	 * @return mixed  The return value generated by the called function
	 */
	function _( $ident )
	{
		static $cache = array();
		$parts = explode( '.', $ident );
		$cName = ( empty($parts) ? 'core' : array_shift($parts) );
		$fName = ( empty($parts) ? 'info' : array_shift($parts) );
		$cName = strtolower($cName);
		
		$retVal = false;
		if( !isset($cache[$cName]) ) {
			$fileName = JPATH_SITE.DS.'components'.DS.'com_arc_'.$cName.DS.'helpers'.DS.'data_access.php';
			if( file_exists($fileName) ) {
				require_once($fileName);
				$cNameFull = 'ApotheosisData_'.ucfirst($cName);
				$cache[$cName] = new $cNameFull();
			}
			else {
				$cache[$cName] = false;
			}
		}
		
		if( is_a($cache[$cName], 'ApotheosisData') && method_exists($cache[$cName], $fName) ) {
			$tmp = func_get_args();
			array_shift( $tmp );
			$args = array();
			foreach( $tmp as $k=>$v ) {
				$args[] = &$tmp[$k];
			}
			$retVal = call_user_func_array( array($cache[$cName], $fName), $args );
		}
		else {
			$retVal = null;
		}
		
		return $retVal;
	}
}
?>